Fix experimental access to extern crates
I can't compile the current code because of the following error:

```
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> rust-numpy/src/array.rs:183:59
    |
183 |     pub unsafe fn from_borrowed_ptr(py: Python, ptr: *mut pyo3::ffi::PyObject) -> &Self {
    |                                                                                                         ^^^^
    |
    = help: add #![feature(extern_prelude)] to the crate attributes to enable
```

Using ffi instead of pyo3::ffi is enough for fixing that.

(question: how does it works on Travis?)